# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a3b3725c73d9f927843c1477159b9ee81091e6b34aac8d1f5624dca0458b60360492d7a10598743dd461b8b88eb266d622854980b2032cfb27487a547355b45

test:
  secret_key_base: 495473c94f2890d31d45aba97a009b22edf664bfa5636b3b4c9f82b2522c932e962673062b4f89bcffa1a4cc51621fb579bed6195c354b212871734323652bc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
